services:
    sportsstore:
        build: .
        ports:
            - "5000:5000"
        environment:
            - ASPNERCORE_ENVIRONMENT=Production
        depends_on:
            - sqlserver
    sqlserver:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Secret123$"
            ACCEPT_EULA: "Y"